In [1]:
# !conda install sqlalchemy --y

In [1]:
# !pip install pymysql

In [2]:
# !pip install cmake cython

In [3]:
# !pip install networkit

In [4]:
import pandas as pd
import sqlalchemy as sql
import numpy as np
import igraph as ig

In [5]:
# connect_string = 'mysql+pymysql://ckg:Admin123@10.200.106.114/umls'
# # 10.200.106.114

In [6]:
connect_string = 'mysql+pymysql://root:Admin123@127.0.0.1/umls'
# 10.200.106.114

In [7]:
sql_engine = sql.create_engine(connect_string)

In [8]:
## Concept

In [9]:
# !pip install igraph

In [10]:
# ig.__version__

In [11]:
import os
os.getcwd()

'/home/wt/Code/snomed'

In [12]:
## Check semantics networks

### UMLS semantic networks

There are two weakly connected components in the network, one for semantic types and the other for relations. In the relations, associated_with has the highest in-degree, meaning that many relations isa associated_with. See below plot:  
![semantic_networks](img/semantic_networks.png)

Also, there are multiple links between the same node pairs. 

The network structure for relations in semantic networks is below, where each link denotes an 'isa' relation, and 'isa' is NOT included in the relation network. 

![sn_relations](img/sn_relations.png)

In [32]:
# UMLS semantic netowrks: SRSTRE2. 
query = '''SELECT * FROM SRSTRE2'''

df = pd.read_sql_query(query, sql_engine)

In [33]:
df.head()

STY1       RL       STY2
0  Acquired Abnormality  affects  Amphibian
1  Acquired Abnormality  affects     Animal
2  Acquired Abnormality  affects   Archaeon
3  Acquired Abnormality  affects  Bacterium
4  Acquired Abnormality  affects       Bird

In [34]:
# df[df['STY2']=='associated_with']

In [35]:
# df[['STY1', 'STY2', 'RL']]

In [36]:
# set(df['RL'])

In [37]:
df.to_csv('data/semantic_networks.csv')

In [16]:
g = ig.Graph.DataFrame(df[['STY1', 'STY2', 'RL']], directed=True)

In [17]:
components = g.clusters(mode='weak')

In [18]:
components.subgraphs()

[<igraph.Graph at 0x7f0ada2a97c0>, <igraph.Graph at 0x7f0ada2a98b0>]

In [19]:
esg = components.subgraphs()[0]

In [20]:
len(set(esg.es['RL']))

49

In [21]:
sg = components.subgraphs()[1]

In [22]:
sg.summary()

'IGRAPH DN-- 53 112 -- \n+ attr: name (v), RL (e)'

In [23]:
set(sg.vs['name']) - set(esg.es['RL'])

{'brings_about',
 'functionally_related_to',
 'physically_related_to',
 'spatially_related_to',
 'temporally_related_to'}

In [24]:
sgs = sg.subgraph([v for v in sg.vs if v['name'] in set(esg.es['RL'])])

In [25]:
sgs.summary()

'IGRAPH DN-- 48 71 -- \n+ attr: name (v), RL (e)'

In [26]:
sgs.vs['kcore'] = sgs.coreness(mode='all')

In [30]:
sgs.vs.select(kcore_ge=2)['name']

['affects',
 'analyzes',
 'assesses_effect_of',
 'associated_with',
 'carries_out',
 'complicates',
 'conceptual_part_of',
 'conceptually_related_to',
 'degree_of',
 'derivative_of',
 'developmental_form_of',
 'diagnoses',
 'disrupts',
 'evaluation_of',
 'exhibits',
 'interacts_with',
 'issue_in',
 'manages',
 'measurement_of',
 'measures',
 'method_of',
 'occurs_in',
 'performs',
 'practices',
 'prevents',
 'process_of',
 'property_of',
 'treats']

In [28]:
1-450/519

0.1329479768786127

In [16]:
g.write_graphml('data/semantic_network.graphml')

### 1. UMLS SCUI (SNOMED)

In [10]:
# Unique name of CUI is "TTY='PN'"
# Unique name of SUIC is TTY='FN', not all ontologies has FN

In [11]:
# Snomed SCUI. 
query = '''SELECT * FROM MRCONSO WHERE TTY='FN' and SAB ='SNOMEDCT_US'
'''

df = pd.read_sql_query(query, sql_engine)

In [12]:
df.sample(3)

CUI  LAT TS       LUI STT       SUI ISPREF       AUI       SAUI  \
187044  C1278968  ENG  S  L2870495  PF  S3279688      Y  A3417827  564631018   
252343  C0058678  ENG  S  L2821026  PF  S3425691      Y  A3573117  807717010   
198203  C0406948  ENG  S  L2859586  PF  S3304012      Y  A3442756  560961019   

             SCUI  SDUI          SAB TTY       CODE  \
187044  181389002  None  SNOMEDCT_US  FN  181389002   
252343   67938008  None  SNOMEDCT_US  FN   67938008   
198203  178094008  None  SNOMEDCT_US  FN  178094008   

                                                   STR  SRL SUPPRESS  CVF  
187044           Entire axillary vein (body structure)    9        N  NaN  
252343            Amnesic shellfish poison (substance)    9        N  NaN  
198203  Excision or aspiration of ganglion (procedure)    9        N  NaN

In [8]:
df['SUPPRESS'].value_counts()

N    346950
Name: SUPPRESS, dtype: int64

In [9]:
df.shape

(346950, 18)

In [24]:
g = df.groupby('SCUI')['STR'].apply(lambda x: len(list(np.unique(x))))

In [25]:
scui_df = g.reset_index()

In [12]:
scui_df['STR'].unique()

array([1])

In [26]:
df.sample(3)

CUI  LAT TS       LUI STT       SUI ISPREF        AUI  \
149453  C0202709  ENG  S  L2914990  PF  S3256257      Y   A3392814   
13030   C1997906  ENG  S  L6922682  PF  S8058733      Y  A13373321   
315032  C0301512  ENG  S  L3124616  PF  S3611124      Y   A3777544   

              SAUI       SCUI  SDUI          SAB TTY       CODE  \
149453   808127013   68306006  None  SNOMEDCT_US  FN   68306006   
13030   2689493010  428397008  None  SNOMEDCT_US  FN  428397008   
315032  1204226018     669007  None  SNOMEDCT_US  FN     669007   

                                                      STR  SRL SUPPRESS  CVF  
149453  Diagnostic radiography of facial bones (proced...    9        N  NaN  
13030   Extension Namespace {1000062} (namespace concept)    9        N  NaN  
315032                   Vaccinia virus vaccine (product)    9        N  NaN

In [13]:
df.to_csv('data/subconcepts.csv', index=None)

In [19]:
df = pd.read_csv('data/subconcepts.csv')

In [20]:
df.shape

(346950, 18)

In [7]:
df['SAB'].unique()

array(['SNOMEDCT_US'], dtype=object)

In [8]:
df.head()

CUI  LAT TS       LUI STT       SUI ISPREF        AUI        SAUI  \
0  C0319824  ENG  S  L2931276  PF  S3204998      Y  A10868589  2615359012   
1  C0006864  ENG  S  L2932443  PF  S3205841      Y  A10868616  2615311012   
2  C0201945  ENG  S  L2949850  PF  S3213573      Y  A10868693  2612635015   
3  C0013336  ENG  S  L2973626  PF  S3235999      Y  A10868877  2615646014   
4  C0600203  ENG  S  L2792355  PF  S3257200      Y  A10869342  2615319014   

        SCUI  SDUI          SAB TTY       CODE  \
0  420643001   NaN  SNOMEDCT_US  FN  420643001   
1  421921003   NaN  SNOMEDCT_US  FN  421921003   
2   77161005   NaN  SNOMEDCT_US  FN   77161005   
3  422065006   NaN  SNOMEDCT_US  FN  422065006   
4  421675006   NaN  SNOMEDCT_US  FN  421675006   

                                                 STR  SRL SUPPRESS     CVF  
0                      Caloscypha fulgens (organism)    9        N     NaN  
1                            Cannabinoid (substance)    9        N     NaN  
2  Cerebrospinal fluid protein electrophoresis (p...    9        N     NaN  
3            Constitutional short stature (disorder)    9        N  2048.0  
4                    Dichloroacetic acid (substance)    9        N     NaN

In [9]:
g = df.groupby('SCUI')['CUI'].apply(lambda x: len(list(np.unique(x))))

In [10]:
scui_df = g.reset_index()

In [12]:
scui_df['CUI'].unique()

array([1])

### UMLS SCUI (ICD-9)

In [115]:
# For the full list of Vocabulary: https://www.nlm.nih.gov/research/umls/sourcereleasedocs/index.html

In [165]:
# ICD SCUI. 
query = '''SELECT * FROM MRCONSO WHERE SAB IN ('ICD9CM') AND SUPPRESS='N'
'''
df = pd.read_sql_query(query, sql_engine)
#'ICD10' , 'ICD9CM', 'ICD10CM')
# AND TTY='PT'

In [166]:
df.sample(3)

CUI  LAT TS        LUI STT        SUI ISPREF        AUI  SAUI  \
4700   C2349612  ENG  P   L7963409  PF   S9304765      Y  A15575190  None   
19511  C0007107  ENG  S   L0590659  PF   S0683819      N   A8360540  None   
9004   C0154529  ENG  P  L10834168  PF  S13470477      N  A20885200  None   

       SCUI    SDUI     SAB TTY    CODE  \
4700   None  679.14  ICD9CM  PT  679.14   
19511  None   161.9  ICD9CM  PT   161.9   
9004   None  305.43  ICD9CM  PT  305.43   

                                                     STR  SRL SUPPRESS  CVF  
4700   Fetal complications from in utero procedure, p...    0        N  NaN  
19511          Malignant neoplasm of larynx, unspecified    0        N  NaN  
9004   Sedative, hypnotic or anxiolytic abuse, in rem...    0        N  NaN

In [167]:
df['SUPPRESS'].value_counts()

N    22406
Name: SUPPRESS, dtype: int64

In [168]:
df['CODE'].nunique()

22406

In [169]:
df[df['SUPPRESS']=='N']['CODE'].nunique()

22406

In [170]:
df[df['CODE'] =='V76.5']

CUI  LAT TS       LUI STT       SUI ISPREF       AUI  SAUI  SCUI  \
3850  C0878740  ENG  P  L1719670  PF  S1967095      Y  A8377314  None  None   

       SDUI     SAB TTY   CODE  \
3850  V76.5  ICD9CM  HT  V76.5   

                                                 STR  SRL SUPPRESS    CVF  
3850  Screening for malignant neoplasms of intestine    0        N  256.0

In [171]:
df.shape

(22406, 18)

In [172]:
g = df.groupby('CODE')['STR'].apply(lambda x: len(list(np.unique(x))))

In [173]:
scui_df = g.reset_index()

In [174]:
scui_df

CODE  STR
0            00    1
1      00-00.99    1
2      00-99.99    1
3          00.0    1
4         00.01    1
...         ...  ...
22401     V91.9    1
22402    V91.90    1
22403    V91.91    1
22404    V91.92    1
22405    V91.99    1

[22406 rows x 2 columns]

In [176]:
scui_df['STR'].unique()

array([1])

In [180]:
df[df['CODE'] =='V91.99']

CUI  LAT TS       LUI STT        SUI ISPREF        AUI  SAUI  SCUI  \
5089  C2921366  ENG  P  L9444086  PF  S11733140      Y  A18090781  None  None   

        SDUI     SAB TTY    CODE  \
5089  V91.99  ICD9CM  PT  V91.99   

                                                    STR  SRL SUPPRESS  CVF  \
5089  Other specified multiple gestation, unable to ...    0        N  NaN   

     other_scui  
5089      V9199

In [181]:
df['other_scui'] = df['CODE'].str.replace('.', '')

In [182]:
df.to_csv('data/icd9-subconcepts.csv', index=None)

In [183]:
df = pd.read_csv('data/icd9-subconcepts.csv')

In [184]:
df.shape

(22406, 19)

In [185]:
df['SAB'].unique()

array(['ICD9CM'], dtype=object)

In [186]:
df.head()

CUI  LAT TS       LUI STT       SUI ISPREF        AUI  SAUI  SCUI  \
0  C0002873  ENG  P  L0002873  PF  S0000506      N  A10862869   NaN   NaN   
1  C0002726  ENG  P  L0002726  PF  S0013420      N  A10862875   NaN   NaN   
2  C0027947  ENG  P  L0027947  PF  S0066573      N  A10862879   NaN   NaN   
3  C0027632  ENG  P  L0027632  PF  S0217799      N  A10862882   NaN   NaN   
4  C0702159  ENG  P  L0003575  PF  S0217910      N  A10862883   NaN   NaN   

    SDUI     SAB TTY   CODE  \
0  285.2  ICD9CM  HT  285.2   
1  277.3  ICD9CM  HT  277.3   
2  288.0  ICD9CM  HT  288.0   
3  238.7  ICD9CM  HT  238.7   
4  284.0  ICD9CM  HT  284.0   

                                                 STR  SRL SUPPRESS    CVF  \
0                          Anemia of chronic disease    0        N  256.0   
1                                        Amyloidosis    0        N  256.0   
2                                        Neutropenia    0        N  256.0   
3  Neoplasm of uncertain behavior of other lympha...    0        N    NaN   
4                     Constitutional aplastic anemia    0        N  256.0   

  other_scui  
0       2852  
1       2773  
2       2880  
3       2387  
4       2840

In [187]:
g = df.groupby('CODE')['CUI'].apply(lambda x: len(list(np.unique(x))))

In [188]:
scui_df = g.reset_index()

In [189]:
scui_df['CUI'].unique()

array([1])

In [190]:
scui_df.head()

CODE  CUI
0        00    1
1  00-00.99    1
2  00-99.99    1
3      00.0    1
4     00.01    1

In [191]:
scui_df['CUI'].unique()

array([1])

### Subconcepts (ICD-10)

In [230]:
# ICD SCUI. 
query = '''SELECT * FROM MRCONSO WHERE SAB IN ('ICD10') AND SUPPRESS='N' 
'''
df = pd.read_sql_query(query, sql_engine)
#'ICD10' , 'ICD9CM', 'ICD10CM')
# AND TTY='PT', 

In [231]:
# # ICD SCUI. 
# query = '''SELECT * FROM MRCONSO WHERE SAB IN ('ICD10CM') AND SUPPRESS='N' 
# '''
# df2 = pd.read_sql_query(query, sql_engine)
# #'ICD10' , 'ICD9CM', 'ICD10CM')
# # AND TTY='PT', 

In [232]:
# set(df2['CODE']).intersection( set(df['CODE']) )

In [233]:
# set(df['CODE']) - set(df2['CODE'])

In [234]:
df.sample(3)

CUI  LAT TS       LUI STT       SUI ISPREF       AUI  SAUI  SCUI  \
1768  C0694481  ENG  P  L1217572  PF  S1458487      Y  A1411733  None  None   
3543  C0549150  ENG  S  L0375030  VC  S0507053      N  A0578793  None  None   
5265  C0476526  ENG  S  L0661171  PF  S0793007      Y  A0852144  None  None   

      SDUI    SAB TTY   CODE  \
1768  None  ICD10  HT    H03   
3543  None  ICD10  PT  L73.1   
5265  None  ICD10  PT  R86.0   

                                                    STR  SRL SUPPRESS    CVF  
1768  Disorders of eyelid in diseases classified els...    3        N    NaN  
3543                          Pseudofolliculitis barbae    3        N  256.0  
5265  Abnormal findings in specimens from male genit...    3        N    NaN

In [235]:
df['SUPPRESS'].value_counts()

N    12318
Name: SUPPRESS, dtype: int64

In [236]:
df['CODE'].nunique()

12318

In [237]:
# df[df['SUPPRESS']=='N']['CODE'].nunique()

In [238]:
g = df.groupby('CODE')['STR'].apply(lambda x: len(list(np.unique(x))))

In [239]:
scui_df = g.reset_index()

In [240]:
scui_df

CODE  STR
0            A00    1
1      A00-A09.9    1
2      A00-B99.9    1
3          A00.0    1
4          A00.1    1
...          ...  ...
12313      Z99.1    1
12314      Z99.2    1
12315      Z99.3    1
12316      Z99.8    1
12317      Z99.9    1

[12318 rows x 2 columns]

In [241]:
scui_df['STR'].unique()

array([1])

In [242]:
scui_df[scui_df['STR'] ==2]

Empty DataFrame
Columns: [CODE, STR]
Index: []

In [243]:
df[df['CODE'] =='C00.0']

CUI  LAT TS       LUI STT       SUI ISPREF       AUI  SAUI  SCUI  \
11943  C0474962  ENG  S  L0571257  PF  S0940554      Y  A0996398  None  None   

       SDUI    SAB TTY   CODE                                       STR  SRL  \
11943  None  ICD10  PX  C00.0  Malignant neoplasm of external upper lip    3   

      SUPPRESS    CVF  
11943        N  256.0

In [244]:
df.to_csv('data/icd10-subconcepts.csv', index=None)

In [245]:
df = pd.read_csv('data/icd10-subconcepts.csv')

In [246]:
df.shape

(12318, 18)

In [247]:
df['SAB'].unique()

array(['ICD10'], dtype=object)

In [248]:
df.head()

CUI  LAT TS       LUI STT       SUI ISPREF       AUI  SAUI  SCUI  \
0  C0026106  ENG  P  L0026106  VC  S0000001      N  A0000002   NaN   NaN   
1  C0026351  ENG  S  L0026351  PF  S0000002      N  A0000008   NaN   NaN   
2  C0036857  ENG  S  L0036857  PF  S0000003      N  A0000014   NaN   NaN   
3  C0020796  ENG  P  L0033296  VC  S0000004      N  A0000020   NaN   NaN   
4  C0025362  ENG  S  L0080273  PF  S0000005      N  A0000026   NaN   NaN   

   SDUI    SAB TTY CODE                             STR  SRL SUPPRESS    CVF  
0   NaN  ICD10  HT  F70         Mild mental retardation    3        N  256.0  
1   NaN  ICD10  HT  F71     Moderate mental retardation    3        N    NaN  
2   NaN  ICD10  HT  F72       Severe mental retardation    3        N  256.0  
3   NaN  ICD10  HT  F73     Profound mental retardation    3        N  256.0  
4   NaN  ICD10  HT  F79  Unspecified mental retardation    3        N    NaN

In [249]:
g = df.groupby('CODE')['CUI'].apply(lambda x: len(list(np.unique(x))))

In [250]:
scui_df = g.reset_index()

In [251]:
scui_df['CUI'].unique()

array([1])

In [252]:
scui_df.head()

CODE  CUI
0        A00    1
1  A00-A09.9    1
2  A00-B99.9    1
3      A00.0    1
4      A00.1    1

In [253]:
scui_df['CUI'].unique()

array([1])

## 2. UMLS Concepts and their prefered names

### 2.1 TUI: definition of semantic types

In [22]:
# https://www.ncbi.nlm.nih.gov/books/NBK9679/table/ch05.T.srdef/. STY = Semantic Type or RL = Relation 
query = "SELECT DISTINCT UI, STY_RL, STN_RTN, DEF FROM SRDEF WHERE RT = 'STY'"

In [23]:
df = pd.read_sql_query(query, sql_engine)

In [24]:
df.head()

UI     STY_RL   STN_RTN  \
0  T001   Organism      A1.1   
1  T002      Plant  A1.1.3.3   
2  T004     Fungus  A1.1.3.2   
3  T005      Virus    A1.1.4   
4  T007  Bacterium    A1.1.2   

                                                 DEF  
0  Generally, a living individual, including all ...  
1  An organism having cellulose cell walls, growi...  
2  A eukaryotic organism characterized by the abs...  
3  An organism consisting of a core of a single n...  
4  A small, typically one-celled, prokaryotic mic...

In [25]:
df.to_csv('data/TUI.csv', index=None)

### 2.2 TUI relations

In [42]:
# SRSTRE1.UI2 = 'T186': isa relation. 
query = '''
SELECT DISTINCT UI1, UI2, UI3 FROM SRSTRE1 INNER JOIN (SELECT DISTINCT UI from SRDEF WHERE RT = 'STY') as Semantics 
ON SRSTRE1.UI1 = Semantics.UI WHERE SRSTRE1.UI2 = 'T186'
'''

In [43]:
df = pd.read_sql_query(query, sql_engine)

In [44]:
df.head()

UI1   UI2   UI3
0  T001  T186  T071
1  T001  T186  T072
2  T002  T186  T001
3  T002  T186  T071
4  T002  T186  T072

In [39]:
df.to_csv('data/TUIRel.csv', index=None)

### 2.3 CUI

In [45]:
query = '''
SELECT DISTINCT CUI, STR, SAB, SUPPRESS from MRCONSO where MRCONSO.ISPREF = 'Y' 
AND MRCONSO.STT = 'PF' AND MRCONSO.TS = 'P' and MRCONSO.LAT = 'ENG'
'''

In [46]:
df = pd.read_sql_query(query, sql_engine)

In [47]:
df.head()

CUI                   STR  SAB SUPPRESS
0  C0011251   Delusional disorder  MTH        N
1  C0030540  Parent-child problem  MTH        N
2  C0042721       Viral hepatitis  MTH        N
3  C0040255       Tinea imbricata  MTH        N
4  C0342122  Toxic diffuse goiter  MTH        N

In [48]:
df['SUPPRESS'].unique()

array(['N', 'O', 'Y', 'E'], dtype=object)

In [49]:
df.to_csv('data/CUIs.csv', index=None)

In [50]:
# # Based on https://www.nlm.nih.gov/research/umls/implementation_resources/query_diagrams/er1.html 
# query = '''
# SELECT * FROM MRCONSO WHERE TS = 'P'
#      AND STT = 'PF'
#      AND ISPREF = 'Y'
#      AND LAT = 'ENG'
# '''
# df = pd.read_sql_query(query, sql_engine)

In [51]:
# df.head()

In [17]:
# g = con.groupby('CUI')['STR'].apply(lambda x: ' | '.join(list(np.unique(x))))

In [52]:
# g = df.groupby('CUI')['STR'].apply(lambda x: len(list(np.unique(x))))

In [53]:
# cui_df = g.reset_index()

In [54]:
# cui_df['STR'].unique()

In [55]:
# cui_df[cui_df['STR'] >1]

In [56]:
# df.shape

In [57]:
# df['SUPPRESS'].value_counts()

In [58]:
# df.to_csv('data/concepts.csv', index=None)

### 2.4 CUI-TUI

## Relation 

### All reltionships

In [5]:
# There are some relations with DIR=NULL, Y, N
# There are only N or O in SUPPRESS
# https://www.ncbi.nlm.nih.gov/books/NBK9684/
# Relationships may be suppressible if considered obsolete, which is indicated by a value of O in the SUPPRESS field.
# There are duplicated relations if without (SUPPRESS='N')
# there is no informative ralations if without RELA 
# If withou DIR, there inverse relationships. 
query = '''
select * from umls.MRREL where (DIR='Y' or DIR IS NULL) AND (SUPPRESS='N') AND (RELA is not null)
'''

df = pd.read_sql_query(query, sql_engine)

In [6]:
# query = "SELECT * FROM umls.SRDEF WHERE rt = 'RL'"
# rel_type = pd.read_sql_query(query, sql_engine)

In [7]:
df['DIR'].value_counts(dropna=False)

NaN    23914946
Y       2537330
Name: DIR, dtype: int64

In [8]:
df.shape

(26452276, 16)

In [9]:
df[df['DIR'].isna()].head()

CUI1      AUI1 STYPE1 REL      CUI2      AUI2 STYPE2          RELA  \
2016  C0025294  A0000677    AUI  RO  C0694469  A1411710    AUI  icd_asterisk   
2017  C0041318  A0239827    AUI  RO  C0694469  A1411710    AUI  icd_asterisk   
2018  C0029871  A0240092    AUI  RO  C0348522  A0679047    AUI  icd_asterisk   
2019  C0039130  A0240174    AUI  RO  C0039130  A0240175    AUI  icd_asterisk   
2020  C0039130  A0240175    AUI  RO  C0039130  A0240174    AUI  icd_asterisk   

            RUI  SRUI      SAB       SL    RG   DIR SUPPRESS  CVF  
2016  R00987462  None  ICD10AM  ICD10AM  None  None        N  NaN  
2017  R00987463  None  ICD10AM  ICD10AM  None  None        N  NaN  
2018  R00987464  None  ICD10AM  ICD10AM  None  None        N  NaN  
2019  R00987465  None  ICD10AM  ICD10AM  None  None        N  NaN  
2020  R00987466  None  ICD10AM  ICD10AM  None  None        N  NaN

In [10]:
df['SUPPRESS'].value_counts(dropna=False)

N    26452276
Name: SUPPRESS, dtype: int64

In [11]:
# df[df['SUPPRESS'] == 'O'].sample(10)

In [12]:
# df = df[df['SUPPRESS'] == 'N']

## Remove duplicated relations

In [13]:
df = df.sort_values(by=['CUI1', 'CUI2'])

In [14]:
df.head()

CUI1       AUI1 STYPE1 REL      CUI2       AUI2 STYPE2  \
296480  C0000039  A11754881    AUI  SY  C0000039   A0016515    AUI   
308025  C0000039   A0016515    AUI  SY  C0000039  A11754881    AUI   
780271  C0000039  A13517167    AUI  SY  C0000039   A8009316    AUI   
787066  C0000039   A8009316    AUI  SY  C0000039  A13517167    AUI   
809414  C0000039  A16467622    AUI  SY  C0000039   A7480660    AUI   

                           RELA         RUI  SRUI     SAB      SL    RG   DIR  \
296480          has_translation  R101796151  None  MSHSWE  MSHSWE  None  None   
308025           translation_of  R101808683  None  MSHSWE  MSHSWE  None  None   
780271  has_transliterated_form  R106649790  None  MSHRUS  MSHRUS  None  None   
787066   transliterated_form_of  R106656931  None  MSHRUS  MSHRUS  None  None   
809414         has_sort_version  R106707842  None  MSHGER  MSHGER  None  None   

       SUPPRESS  CVF  
296480        N  NaN  
308025        N  NaN  
780271        N  NaN  
787066        N  NaN  
809414        N  NaN

In [15]:
# df[df.duplicated(['CUI1', 'CUI2', 'RELA'])]

In [16]:
# remove  duplicated relationships
df = df.drop_duplicates(['CUI1', 'CUI2', 'RELA'])

In [17]:
df.shape

(16252514, 16)

In [18]:
# remove self link
df = df[df['CUI1'] != df['CUI2']]

In [19]:
df.shape

(14548762, 16)

In [20]:
# remove null relations
# df = df[df['RELA'].isna()==False]

In [21]:
df.shape

(14548762, 16)

In [22]:
df['RELA'].unique()

array(['mapped_to', 'has_component', 'measures', 'parent_of', 'form_of',
       'exhibited_by', 'inverse_isa', 'see', 'has_causative_agent',
       'entry_combination_of', 'see_from', 'isa', 'used_for',
       'has_direct_substance', 'replaced_by', 'subset_includes_concept',
       'same_as', 'has_tradename', 'has_ingredient',
       'precise_ingredient_of', 'mapping_qualifier_of', 'mapped_from',
       'may_be_prevented_by', 'may_be_treated_by',
       'has_contraindicated_drug', 'has_member',
       'chemotherapy_regimen_has_component', 'has_product_component',
       'has_basis_of_strength_substance', 'has_active_ingredient',
       'has_precise_active_ingredient', 'use', 'tradename_of',
       'has_active_moiety', 'lab_number_of', 'has_part', 'contains',
       'physiologic_effect_of', 'mechanism_of_action_of',
       'chemical_structure_of', 'structural_class_of',
       'has_inactive_ingredient',
       'biological_process_involves_gene_product',
       'is_biochemical_function_o

In [23]:
df['DIR'].value_counts(dropna=False)

NaN    13225880
Y       1322882
Name: DIR, dtype: int64

In [24]:
df.to_csv('data/relations.csv', index=None)

In [5]:
df = pd.read_csv('data/relations.csv')

/home/ubuntu/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (9,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [6]:
df.head()

CUI1       AUI1 STYPE1 REL      CUI2       AUI2 STYPE2           RELA  \
0  C0000039   A0016515   SDUI  RN  C0043950   A0137399   SDUI      mapped_to   
1  C0000039   A0016515   SDUI  RN  C0216971   A0376033   SDUI      mapped_to   
2  C0000039  A18399186   SCUI  RO  C0364349  A18182073   SCUI  has_component   
3  C0000039  A23513030   SCUI  RO  C0364349  A18182073   SCUI       measures   
4  C0000039   A0016515   SDUI  RN  C0381030   A0683149   SDUI      mapped_to   

          RUI SRUI  SAB   SL   RG  DIR SUPPRESS  CVF  
0  R148171650  NaN  MSH  MSH  1.0  NaN        N  NaN  
1  R148183528  NaN  MSH  MSH  1.0  NaN        N  NaN  
2  R165238590  NaN  LNC  LNC  NaN  NaN        N  NaN  
3  R167106427  NaN  LNC  LNC  NaN  NaN        N  NaN  
4  R148166148  NaN  MSH  MSH  1.0  NaN        N  NaN

In [13]:
df[(df['CUI2']=='C0022658') &  (df['CUI1']=='C1335036')]

CUI1       AUI1 STYPE1  REL      CUI2       AUI2 STYPE2  \
7580167  C1335036  A25769044   SCUI  PAR  C0022658  A25760652   SCUI   
7580168  C1335036  A25769044   SCUI  CHD  C0022658   A7568258   SCUI   

                RELA        RUI SRUI  SAB   SL  RG  DIR SUPPRESS  CVF  
7580167  inverse_isa  R69823779  NaN  NCI  NCI NaN  NaN        N  NaN  
7580168          isa  R69846454  NaN  NCI  NCI NaN  NaN        N  NaN

In [14]:
df[(df['CUI1']=='C0022658') &  (df['CUI2']=='C1335036')]

CUI1       AUI1 STYPE1  REL      CUI2       AUI2 STYPE2  \
950660  C0022658   A7568258   SCUI  PAR  C1335036  A25769044   SCUI   
950661  C0022658  A25760652   SCUI  CHD  C1335036  A25769044   SCUI   

               RELA        RUI SRUI  SAB   SL  RG  DIR SUPPRESS  CVF  
950660  inverse_isa  R69794135  NaN  NCI  NCI NaN  NaN        N  NaN  
950661          isa  R69802575  NaN  NCI  NCI NaN  NaN        N  NaN

In [24]:
df['RELA'].nunique()

822

In [25]:
df['RELA'].nunique()

822

## Semantic Type

In [28]:
# query = """
# select * from MRSTY where CUI in 
# (select distinct CUI from MRCONSO WHERE SUPPRESS='N' AND LAT = 'ENG' 
# AND TS = 'P' AND ISPREF = 'Y' AND SAB ='SNOMEDCT_US')
# """

query = """
select * from MRSTY
"""


df = pd.read_sql_query(query, sql_engine)

In [29]:
df.head()

CUI   TUI       STN                           STY        ATUI    CVF
0  C0070474  T104  A1.4.1.2  Chemical Viewed Structurally  AT07863947  256.0
1  C0678518  T104  A1.4.1.2  Chemical Viewed Structurally  AT07863951  256.0
2  C0684279  T104  A1.4.1.2  Chemical Viewed Structurally  AT07863958  256.0
3  C0684298  T104  A1.4.1.2  Chemical Viewed Structurally  AT07863959  256.0
4  C0684300  T104  A1.4.1.2  Chemical Viewed Structurally  AT07863960  256.0

In [30]:
df = df[['CUI', 'TUI', 'STN', 'STY']]

In [31]:
df.head()

CUI   TUI       STN                           STY
0  C0070474  T104  A1.4.1.2  Chemical Viewed Structurally
1  C0678518  T104  A1.4.1.2  Chemical Viewed Structurally
2  C0684279  T104  A1.4.1.2  Chemical Viewed Structurally
3  C0684298  T104  A1.4.1.2  Chemical Viewed Structurally
4  C0684300  T104  A1.4.1.2  Chemical Viewed Structurally

In [32]:
df.to_csv('data/semantype.csv', index=None)

In [33]:
df = pd.read_csv('data/semantype.csv')

In [34]:
g = df.groupby('CUI')['TUI'].apply(lambda x: len(list(np.unique(x))))

In [35]:
sty_df = g.reset_index()

In [36]:
sty_df['TUI'].unique()


array([3, 2, 1, 4])

In [37]:
df = df.drop_duplicates(['TUI', 'STY'])

In [38]:
df.head()

CUI   TUI           STN                           STY
0      C0070474  T104      A1.4.1.2  Chemical Viewed Structurally
78     C0678220  T201        A2.3.1            Clinical Attribute
31148  C0337636  T057          B1.3         Occupational Activity
31430  C0302897  T103        A1.4.1                      Chemical
31432  C0010596  T013  A1.1.3.1.1.3                          Fish

In [39]:
df.to_csv('data/stypes.csv', index=None)

In [21]:
df = pd.read_csv('data/stypes.csv')

In [22]:
df.shape

(127, 4)

In [44]:
g = df.groupby('TUI')['STY'].apply(lambda x: len(list(np.unique(x))))

In [45]:
sty_df = g.reset_index()

In [46]:
sty_df['STY'].unique()


array([1])

In [47]:
sty_df[sty_df['STY'] > 1]

Empty DataFrame
Columns: [TUI, STY]
Index: []

### Load to neo4j by cypher-shell

#### Avoid empty fields, otherwise the nodes cannot be ingested to neo4j

In [ ]:
cypher-shell -u neo4j -p NeO4J 

In [ ]:
# Concepts
CREATE CONSTRAINT ON (c:Concepts) ASSERT c.id IS UNIQUE;
CREATE INDEX ON :Concepts(cui); // 2 ms
    
USING PERIODIC COMMIT 500
LOAD csv with headers from "file:///home/ubuntu/snomed/data/concepts.csv" as line
with line
MERGE (:Concepts
        { id: line.CUI, cui: line.CUI, name: line.STR});

In [171]:
# MATCH (n:Concepts)
# DETACH DELETE n; 

In [ ]:
# atom for Snomed
CREATE CONSTRAINT ON (c:Terms) ASSERT c.id IS UNIQUE;
CREATE INDEX ON :Terms(code); // 2 ms
    
USING PERIODIC COMMIT 500
LOAD csv with headers from "file:///home/ubuntu/snomed/data/subconcepts.csv" as line
with line
MERGE (:Terms
        {id: line.AUI, aui: line.AUI, code: line.CODE, name: line.STR, vocabulary: line.SAB});

In [ ]:
# ICD9CM:  Terms: change SCUI to CODE
CREATE INDEX ON :Terms(other_code); // 2 ms
USING PERIODIC COMMIT 500
LOAD csv with headers from "file:///home/ubuntu/snomed/data/icd9-subconcepts.csv" as line
with line
MERGE (:Terms
        {id: line.AUI, aui: line.AUI, code: line.CODE, other_code: line.other_scui, name: line.STR, vocabulary: line.SAB});

In [ ]:
# ICD10:  Terms: change SCUI to CODE

USING PERIODIC COMMIT 500
LOAD csv with headers from "file:///home/ubuntu/snomed/data/icd10-subconcepts.csv" as line
with line
MERGE (:Terms
        {id: line.AUI, aui: line.AUI, code: line.CODE, name: line.STR, vocabulary: line.SAB});

In [172]:
# MATCH (n:Terms)
# DETACH DELETE n; 

In [ ]:
# scui_2_cui SNOMED
USING PERIODIC COMMIT 500
LOAD CSV WITH HEADERS FROM "file:///home/ubuntu/snomed/data/subconcepts.csv" AS csvLine
MATCH (con:Concepts {id: csvLine.CUI}),(subc:Terms {id: csvLine.AUI})
MERGE (subc)-[:aui_2_cui]->(con);

In [ ]:
# scui_2_cui ICD9CM
USING PERIODIC COMMIT 500
LOAD CSV WITH HEADERS FROM "file:///home/ubuntu/snomed/data/icd9-subconcepts.csv" AS csvLine
MATCH (con:Concepts {id: csvLine.CUI}),(subc:Terms {id: csvLine.AUI})
MERGE (subc)-[:aui_2_cui]->(con);

In [ ]:
# scui_2_cui ICD9CM
USING PERIODIC COMMIT 500
LOAD CSV WITH HEADERS FROM "file:///home/ubuntu/snomed/data/icd10-subconcepts.csv" AS csvLine
MATCH (con:Concepts {id: csvLine.CUI}),(subc:Terms {id: csvLine.AUI})
MERGE (subc)-[:aui_2_cui]->(con);

In [173]:
# MATCH (r:scui_2_cui)
# DELETE r; 

In [19]:
df = pd.read_csv('data/relations.csv')

In [20]:
sum(df['REL'].isna())

0

In [ ]:
# cui_2_cui
# Change order of CUI1 and CUI2
USING PERIODIC COMMIT 500
LOAD CSV WITH HEADERS FROM "file:///home/ubuntu/snomed/data/relations.csv" AS csvLine
MATCH (con1:Concepts {id: csvLine.CUI1}),(con2:Concepts {id: csvLine.CUI2})
MERGE (con1)<-[:cui_2_cui {relation: csvLine.RELA, general_relation: csvLine.REL}]-(con2);

In [174]:
# MATCH (r:cui_2_cui)
# DELETE r; 

In [14]:
df = pd.read_csv('data/stypes.csv')

In [17]:
sum(df['STN'].isna())

0

In [ ]:
# Drop INDEX ON :SemanticTypes(tui)
# Drop CONSTRAINT ON (c:SemanticTypes) ASSERT c.id IS UNIQUE

In [ ]:
# Semantic_type
CREATE CONSTRAINT ON (c:Types) ASSERT c.id IS UNIQUE;
CREATE INDEX ON :Types(tui); // 2 ms
    
USING PERIODIC COMMIT 500
LOAD csv with headers from "file:///home/ubuntu/snomed/data/stypes.csv" as line
with line
MERGE (:Types
        { id: line.TUI, tui: line.TUI, name: line.STY, chapter: line.STN} );

In [18]:
df = pd.read_csv('data/semantype.csv')

In [ ]:
sum(df['STN'].isna())

In [ ]:
USING PERIODIC COMMIT 500
LOAD CSV WITH HEADERS FROM "file:///home/ubuntu/snomed/data/semantype.csv" AS csvLine
MATCH (con1:Concepts {id: csvLine.CUI}),(con2:Types {id: csvLine.TUI})
MERGE (con1)-[:cui_2_tui]->(con2);

In [175]:
# MATCH (n:SemanticTypes)
# DETACH DELETE n; 

In [176]:
# MATCH (r:cui_2_tui)
# DELETE r; 